# Generated by Django 4.1.7 on 2023-03-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_api', '0002_alter_treatment_end_date_alter_treatment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_api.patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_api.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ManyToManyField(through='hospital_api.Prescription', to='hospital_api.treatment'),
        ),
    ]
