# Generated by Django 4.1.7 on 2023-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_api', '0004_treatmentapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=255)),
                ('description', models.TextField(default='none')),
            ],
        ),
    ]
