# Generated by Django 4.1.7 on 2023-03-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_api', '0005_assistant2_treatment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistant2',
        ),
        migrations.DeleteModel(
            name='Treatment2',
        ),
    ]
