# Generated by Django 4.1.7 on 2023-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_api', '0007_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
