# Generated by Django 4.1.7 on 2023-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_api', '0009_remove_doctor_is_doctor_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
